# CRIE UMA COLECTION DO TIPO HASH E PERMITA QUE O USUARIO
# CRIE 3 ELEMENTOS INFORMANDO A CHAVE O O VALOR, NO FINAL DO PROGRAMA
# PARA CADA UM DESSES ELEMENTOS IMPRIMA A FRASE "UMA DAS CHAVES É ****
# E O SEU VALOR É ****"
